/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apptokoroti;

/**
 *
 * @author Rexx
 */
public class UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UI.class.getName());

    /**
     * Creates new form UI
     */
    public UI() {
    initComponents();

    tabUtama.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {

        @Override
        protected int calculateTabAreaHeight(
            int tabPlacement,
            int horizRunCount,
            int maxTabHeight
        ) {
            return 0;
        }

        @Override
        protected void paintTabArea(
            java.awt.Graphics g,
            int tabPlacement,
            int selectedIndex
        ) {
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        tabUtama = new javax.swing.JTabbedPane();
        mainMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tambahProduk = new javax.swing.JPanel();
        tambahKodeProduk = new javax.swing.JTextField();
        tambahNamaProduk = new javax.swing.JTextField();
        tambahJenisProduk = new javax.swing.JTextField();
        tambahHargaProduk = new javax.swing.JTextField();
        bTambahProduk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        editProduk = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cariEditKodeProduk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bCariEditProduk = new javax.swing.JButton();
        editKodeProduk = new javax.swing.JTextField();
        editNamaProduk = new javax.swing.JTextField();
        editJenisProduk = new javax.swing.JTextField();
        editHargaProduk = new javax.swing.JTextField();
        bSimpanEditProduk = new javax.swing.JButton();
        bHapusProduk = new javax.swing.JButton();
        lihatProduk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cariLihatProduk = new javax.swing.JTextField();
        bCariLihatProduk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textLihatProduk = new javax.swing.JTextArea();
        tambahKaryawan = new javax.swing.JPanel();
        addKodeKaryawan = new javax.swing.JTextField();
        addNamaKaryawan = new javax.swing.JTextField();
        addLevelKaryawan = new javax.swing.JTextField();
        addGajiKaryawan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bTambahKaryawan = new javax.swing.JButton();
        editKaryawan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cariEditKodeKaryawan = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        editKodeKaryawan = new javax.swing.JTextField();
        editNamaKaryawan = new javax.swing.JTextField();
        editLevelKaryawan = new javax.swing.JTextField();
        editGajiKaryawan = new javax.swing.JTextField();
        bSimpanEditKaryawan = new javax.swing.JButton();
        bHapusKaryawan = new javax.swing.JButton();
        lihatKaryawan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cariLihatKaryawan = new javax.swing.JTextField();
        bCariLihatKaryawan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textLihatKaryawan = new javax.swing.JTextArea();
        navMainMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        navTambahProduk = new javax.swing.JButton();
        navLihatProduk = new javax.swing.JButton();
        navEditProduk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        navTambahKaryawan = new javax.swing.JButton();
        navLihatKaryawan = new javax.swing.JButton();
        navEditKaryawan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rexx\\Documents\\NetBeansProjects\\Laila\\AppTokoRoti\\src\\main\\resources\\assets\\Untitled-3.png")); // NOI18N

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(256, 256, 256))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab1", mainMenu);

        tambahKodeProduk.setText("Masukkan kode produk");
        tambahKodeProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tambahKodeProdukInputMethodTextChanged(evt);
            }
        });
        tambahKodeProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKodeProdukActionPerformed(evt);
            }
        });

        tambahNamaProduk.setText("Masukkan nama produk");
        tambahNamaProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tambahNamaProdukInputMethodTextChanged(evt);
            }
        });

        tambahJenisProduk.setText("Masukkan jenis produk");
        tambahJenisProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tambahJenisProdukInputMethodTextChanged(evt);
            }
        });

        tambahHargaProduk.setText("Masukkan harga produk");
        tambahHargaProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tambahHargaProdukInputMethodTextChanged(evt);
            }
        });

        bTambahProduk.setText("Simpan");
        bTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahProdukActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tambah Produk");

        javax.swing.GroupLayout tambahProdukLayout = new javax.swing.GroupLayout(tambahProduk);
        tambahProduk.setLayout(tambahProdukLayout);
        tambahProdukLayout.setHorizontalGroup(
            tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahProdukLayout.createSequentialGroup()
                .addGroup(tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bTambahProduk)
                        .addComponent(tambahHargaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tambahJenisProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tambahProdukLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tambahNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahProdukLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(tambahKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tambahProdukLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel5)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        tambahProdukLayout.setVerticalGroup(
            tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahProdukLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahJenisProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahHargaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTambahProduk)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab2", tambahProduk);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Edit Produk");

        cariEditKodeProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cariEditKodeProdukInputMethodTextChanged(evt);
            }
        });

        jLabel7.setText("Masukkan kode produk");

        bCariEditProduk.setText("Cari");
        bCariEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariEditProdukActionPerformed(evt);
            }
        });

        editKodeProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editKodeProdukInputMethodTextChanged(evt);
            }
        });

        editNamaProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editNamaProdukInputMethodTextChanged(evt);
            }
        });

        editJenisProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editJenisProdukInputMethodTextChanged(evt);
            }
        });
        editJenisProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJenisProdukActionPerformed(evt);
            }
        });

        editHargaProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editHargaProdukInputMethodTextChanged(evt);
            }
        });

        bSimpanEditProduk.setText("Simpan");
        bSimpanEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanEditProdukActionPerformed(evt);
            }
        });

        bHapusProduk.setText("Hapus Produk");
        bHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editProdukLayout = new javax.swing.GroupLayout(editProduk);
        editProduk.setLayout(editProdukLayout);
        editProdukLayout.setHorizontalGroup(
            editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProdukLayout.createSequentialGroup()
                .addGroup(editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProdukLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editProdukLayout.createSequentialGroup()
                                .addComponent(bHapusProduk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSimpanEditProduk))
                            .addGroup(editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bCariEditProduk)
                                .addComponent(cariEditKodeProduk)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editKodeProduk)
                                .addComponent(editNamaProduk)
                                .addComponent(editJenisProduk)
                                .addComponent(editHargaProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))))
                    .addGroup(editProdukLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel6)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        editProdukLayout.setVerticalGroup(
            editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProdukLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariEditKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCariEditProduk)
                .addGap(18, 18, 18)
                .addComponent(editKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editJenisProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editHargaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpanEditProduk)
                    .addComponent(bHapusProduk))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab3", editProduk);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Lihat Produk");

        cariLihatProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cariLihatProdukInputMethodTextChanged(evt);
            }
        });

        bCariLihatProduk.setText("Cari");
        bCariLihatProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariLihatProdukActionPerformed(evt);
            }
        });

        textLihatProduk.setColumns(20);
        textLihatProduk.setRows(5);
        textLihatProduk.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textLihatProdukInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(textLihatProduk);

        javax.swing.GroupLayout lihatProdukLayout = new javax.swing.GroupLayout(lihatProduk);
        lihatProduk.setLayout(lihatProdukLayout);
        lihatProdukLayout.setHorizontalGroup(
            lihatProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatProdukLayout.createSequentialGroup()
                .addGroup(lihatProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCariLihatProduk)
                    .addGroup(lihatProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lihatProdukLayout.createSequentialGroup()
                            .addGap(314, 314, 314)
                            .addComponent(jLabel8))
                        .addGroup(lihatProdukLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(cariLihatProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        lihatProdukLayout.setVerticalGroup(
            lihatProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatProdukLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariLihatProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCariLihatProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab5", lihatProduk);

        addKodeKaryawan.setText("Masukkan kode karyawan");
        addKodeKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                addKodeKaryawanInputMethodTextChanged(evt);
            }
        });
        addKodeKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKodeKaryawanActionPerformed(evt);
            }
        });

        addNamaKaryawan.setText("Masukkan nama karyawan");
        addNamaKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                addNamaKaryawanInputMethodTextChanged(evt);
            }
        });

        addLevelKaryawan.setText("Masukkan level karyawan");
        addLevelKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                addLevelKaryawanInputMethodTextChanged(evt);
            }
        });

        addGajiKaryawan.setText("Masukkan gaji karyawan");
        addGajiKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                addGajiKaryawanInputMethodTextChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tambah Karyawan");

        bTambahKaryawan.setText("Tambah");
        bTambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahKaryawanLayout = new javax.swing.GroupLayout(tambahKaryawan);
        tambahKaryawan.setLayout(tambahKaryawanLayout);
        tambahKaryawanLayout.setHorizontalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahKaryawanLayout.createSequentialGroup()
                .addGroup(tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTambahKaryawan)
                    .addComponent(addGajiKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLevelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tambahKaryawanLayout.createSequentialGroup()
                            .addGap(318, 318, 318)
                            .addComponent(jLabel9))
                        .addGroup(tambahKaryawanLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(addKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        tambahKaryawanLayout.setVerticalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahKaryawanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addLevelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addGajiKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTambahKaryawan)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab6", tambahKaryawan);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Edit Karyawan");

        jLabel11.setText("Masukkan kode karyawan");

        cariEditKodeKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cariEditKodeKaryawanInputMethodTextChanged(evt);
            }
        });

        jButton13.setText("Cari");

        editKodeKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editKodeKaryawanInputMethodTextChanged(evt);
            }
        });

        editNamaKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editNamaKaryawanInputMethodTextChanged(evt);
            }
        });

        editLevelKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editLevelKaryawanInputMethodTextChanged(evt);
            }
        });

        editGajiKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editGajiKaryawanInputMethodTextChanged(evt);
            }
        });

        bSimpanEditKaryawan.setText("Simpan");
        bSimpanEditKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanEditKaryawanActionPerformed(evt);
            }
        });

        bHapusKaryawan.setText("Hapus");
        bHapusKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editKaryawanLayout = new javax.swing.GroupLayout(editKaryawan);
        editKaryawan.setLayout(editKaryawanLayout);
        editKaryawanLayout.setHorizontalGroup(
            editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editKaryawanLayout.createSequentialGroup()
                .addGroup(editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editKaryawanLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel10))
                    .addGroup(editKaryawanLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editKaryawanLayout.createSequentialGroup()
                                .addComponent(bHapusKaryawan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSimpanEditKaryawan))
                            .addGroup(editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton13)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cariEditKodeKaryawan)
                                .addComponent(editKodeKaryawan)
                                .addComponent(editNamaKaryawan)
                                .addComponent(editLevelKaryawan)
                                .addComponent(editGajiKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        editKaryawanLayout.setVerticalGroup(
            editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editKaryawanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariEditKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editLevelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editGajiKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpanEditKaryawan)
                    .addComponent(bHapusKaryawan))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab7", editKaryawan);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Lihat Karyawan");

        cariLihatKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cariLihatKaryawanInputMethodTextChanged(evt);
            }
        });

        bCariLihatKaryawan.setText("Cari");
        bCariLihatKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariLihatKaryawanActionPerformed(evt);
            }
        });

        textLihatKaryawan.setColumns(20);
        textLihatKaryawan.setRows(5);
        textLihatKaryawan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textLihatKaryawanInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(textLihatKaryawan);

        javax.swing.GroupLayout lihatKaryawanLayout = new javax.swing.GroupLayout(lihatKaryawan);
        lihatKaryawan.setLayout(lihatKaryawanLayout);
        lihatKaryawanLayout.setHorizontalGroup(
            lihatKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lihatKaryawanLayout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(329, 329, 329))
            .addGroup(lihatKaryawanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lihatKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addComponent(bCariLihatKaryawan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cariLihatKaryawan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lihatKaryawanLayout.setVerticalGroup(
            lihatKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatKaryawanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariLihatKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCariLihatKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab9", lihatKaryawan);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabUtama, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabUtama)
        );

        navMainMenu.setText("Main Menu");
        navMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navMainMenuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kelola Produk");

        navTambahProduk.setText("Tambah Produk");
        navTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navTambahProdukActionPerformed(evt);
            }
        });

        navLihatProduk.setText("Lihat Produk");
        navLihatProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLihatProdukActionPerformed(evt);
            }
        });

        navEditProduk.setText("Edit Produk");
        navEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navEditProdukActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kelola Karyawan");

        navTambahKaryawan.setText("Tambah Karyawan");
        navTambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navTambahKaryawanActionPerformed(evt);
            }
        });

        navLihatKaryawan.setText("Lihat Karyawan");
        navLihatKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLihatKaryawanActionPerformed(evt);
            }
        });

        navEditKaryawan.setText("Edit Karyawan");
        navEditKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navEditKaryawanActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rexx\\Documents\\NetBeansProjects\\Laila\\AppTokoRoti\\src\\main\\resources\\assets\\Untitled-2.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navTambahProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navLihatProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navEditProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navTambahKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(navLihatKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navEditKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)))
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navTambahProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navLihatProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navEditProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navTambahKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navLihatKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navEditKaryawan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahKodeProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKodeProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahKodeProdukActionPerformed
    // button cari di edit produk
    private void bCariEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariEditProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariEditProdukActionPerformed

    private void editJenisProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJenisProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJenisProdukActionPerformed
    // button cari di menu lihat produk
    private void bCariLihatProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariLihatProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariLihatProdukActionPerformed

    private void addKodeKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKodeKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addKodeKaryawanActionPerformed

    private void navMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navMainMenuActionPerformed
        tabUtama.setSelectedComponent(mainMenu);
    }//GEN-LAST:event_navMainMenuActionPerformed

    private void navTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navTambahProdukActionPerformed
        tabUtama.setSelectedComponent(tambahProduk);
    }//GEN-LAST:event_navTambahProdukActionPerformed

    private void navLihatProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLihatProdukActionPerformed
        tabUtama.setSelectedComponent(lihatProduk);
    }//GEN-LAST:event_navLihatProdukActionPerformed

    private void navEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navEditProdukActionPerformed
        tabUtama.setSelectedComponent(editProduk);
    }//GEN-LAST:event_navEditProdukActionPerformed

    private void navTambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navTambahKaryawanActionPerformed
        tabUtama.setSelectedComponent(tambahKaryawan);
    }//GEN-LAST:event_navTambahKaryawanActionPerformed

    private void navLihatKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLihatKaryawanActionPerformed
        tabUtama.setSelectedComponent(lihatKaryawan);
    }//GEN-LAST:event_navLihatKaryawanActionPerformed

    private void navEditKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navEditKaryawanActionPerformed
        tabUtama.setSelectedComponent(editKaryawan);
    }//GEN-LAST:event_navEditKaryawanActionPerformed
    // button di menu tambah produk
    private void bTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTambahProdukActionPerformed
    // button hapus produk
    private void bHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusProdukActionPerformed
    // button simpan di menu edit produk
    private void bSimpanEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanEditProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSimpanEditProdukActionPerformed
    //button tambah karyawan
    private void bTambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTambahKaryawanActionPerformed
    // button hapus karyawan
    private void bHapusKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusKaryawanActionPerformed
    // button simpan di edit karyawan
    private void bSimpanEditKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanEditKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSimpanEditKaryawanActionPerformed
    // button cari di lihat karyawan
    private void bCariLihatKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariLihatKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariLihatKaryawanActionPerformed
    // text field kode produk di tambah produk
    private void tambahKodeProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tambahKodeProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahKodeProdukInputMethodTextChanged
    // text field nama produk di tambah produk
    private void tambahNamaProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tambahNamaProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahNamaProdukInputMethodTextChanged
    // text field jenis produk di tambah produk
    private void tambahJenisProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tambahJenisProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahJenisProdukInputMethodTextChanged
    // text field harga produk di tambah produk
    private void tambahHargaProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tambahHargaProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahHargaProdukInputMethodTextChanged
    // text field cari kode produk di edit produk
    private void cariEditKodeProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cariEditKodeProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cariEditKodeProdukInputMethodTextChanged
    // text field kode produk di edit produk
    private void editKodeProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editKodeProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editKodeProdukInputMethodTextChanged
    // text field nama produk di edit produk
    private void editNamaProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editNamaProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editNamaProdukInputMethodTextChanged
    // text field jenis produk di edit produk
    private void editJenisProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editJenisProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editJenisProdukInputMethodTextChanged
    // text field harga produk di edit produk
    private void editHargaProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editHargaProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editHargaProdukInputMethodTextChanged
    // text field cari produk di lihat produk
    private void cariLihatProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cariLihatProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cariLihatProdukInputMethodTextChanged
    // text area (output) produk di lihat produk
    private void textLihatProdukInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textLihatProdukInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_textLihatProdukInputMethodTextChanged
    // text field kode karyawan di tambah karyawan
    private void addKodeKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_addKodeKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addKodeKaryawanInputMethodTextChanged
    // text field nama karyawan di tambah karyawan
    private void addNamaKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_addNamaKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addNamaKaryawanInputMethodTextChanged
    // text field level karyawan di tambah karyawan
    private void addLevelKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_addLevelKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addLevelKaryawanInputMethodTextChanged
    // text field gaji karyawan di tambah karyawan
    private void addGajiKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_addGajiKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addGajiKaryawanInputMethodTextChanged
    // text field cari kode karyawan di edit karyawan
    private void cariEditKodeKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cariEditKodeKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cariEditKodeKaryawanInputMethodTextChanged
    // text field kode karyawan di edit karyawan
    private void editKodeKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editKodeKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editKodeKaryawanInputMethodTextChanged
    // text field nama karyawan di edit karyawan
    private void editNamaKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editNamaKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editNamaKaryawanInputMethodTextChanged
    // text field level karyawan di edit karyawan
    private void editLevelKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editLevelKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editLevelKaryawanInputMethodTextChanged
    // text field gaji karyawan di edit karyawan
    private void editGajiKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editGajiKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editGajiKaryawanInputMethodTextChanged
    // text field cari kode karyawan di lihat karyawan
    private void cariLihatKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cariLihatKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cariLihatKaryawanInputMethodTextChanged
    // text area (output) karyawan di lihat karyawan
    private void textLihatKaryawanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textLihatKaryawanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_textLihatKaryawanInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addGajiKaryawan;
    private javax.swing.JTextField addKodeKaryawan;
    private javax.swing.JTextField addLevelKaryawan;
    private javax.swing.JTextField addNamaKaryawan;
    private javax.swing.JButton bCariEditProduk;
    private javax.swing.JButton bCariLihatKaryawan;
    private javax.swing.JButton bCariLihatProduk;
    private javax.swing.JButton bHapusKaryawan;
    private javax.swing.JButton bHapusProduk;
    private javax.swing.JButton bSimpanEditKaryawan;
    private javax.swing.JButton bSimpanEditProduk;
    private javax.swing.JButton bTambahKaryawan;
    private javax.swing.JButton bTambahProduk;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField cariEditKodeKaryawan;
    private javax.swing.JTextField cariEditKodeProduk;
    private javax.swing.JTextField cariLihatKaryawan;
    private javax.swing.JTextField cariLihatProduk;
    private javax.swing.JTextField editGajiKaryawan;
    private javax.swing.JTextField editHargaProduk;
    private javax.swing.JTextField editJenisProduk;
    private javax.swing.JPanel editKaryawan;
    private javax.swing.JTextField editKodeKaryawan;
    private javax.swing.JTextField editKodeProduk;
    private javax.swing.JTextField editLevelKaryawan;
    private javax.swing.JTextField editNamaKaryawan;
    private javax.swing.JTextField editNamaProduk;
    private javax.swing.JPanel editProduk;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lihatKaryawan;
    private javax.swing.JPanel lihatProduk;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton navEditKaryawan;
    private javax.swing.JButton navEditProduk;
    private javax.swing.JButton navLihatKaryawan;
    private javax.swing.JButton navLihatProduk;
    private javax.swing.JButton navMainMenu;
    private javax.swing.JButton navTambahKaryawan;
    private javax.swing.JButton navTambahProduk;
    private javax.swing.JTabbedPane tabUtama;
    private javax.swing.JTextField tambahHargaProduk;
    private javax.swing.JTextField tambahJenisProduk;
    private javax.swing.JPanel tambahKaryawan;
    private javax.swing.JTextField tambahKodeProduk;
    private javax.swing.JTextField tambahNamaProduk;
    private javax.swing.JPanel tambahProduk;
    private javax.swing.JTextArea textLihatKaryawan;
    private javax.swing.JTextArea textLihatProduk;
    // End of variables declaration//GEN-END:variables
}
