/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apptokoroti;

/**
 *
 * @author Rexx
 */
public class UI_Manager extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UI_Manager.class.getName());

    /**
     * Creates new form UI
     */
    public UI_Manager() {
    initComponents();

    tabUtama.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {

        @Override
        protected int calculateTabAreaHeight(
            int tabPlacement,
            int horizRunCount,
            int maxTabHeight
        ) {
            return 0;
        }

        @Override
        protected void paintTabArea(
            java.awt.Graphics g,
            int tabPlacement,
            int selectedIndex
        ) {
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        tabUtama = new javax.swing.JTabbedPane();
        mainMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelTambah = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tambahBahanBaku = new javax.swing.JButton();
        inputTelur = new javax.swing.JTextField();
        inputTerigu = new javax.swing.JTextField();
        inputGaram = new javax.swing.JTextField();
        inputGula = new javax.swing.JTextField();
        inputSusu = new javax.swing.JTextField();
        panelEdit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bCariEditProduk = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taEdit = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        cariEdit = new javax.swing.JTextField();
        editJumlah = new javax.swing.JTextField();
        bSimpanEdit = new javax.swing.JButton();
        panelLihat = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bCariLihatProduk = new javax.swing.JButton();
        cariBahan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputLihat = new javax.swing.JTextArea();
        navMainMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        navTambahBahan = new javax.swing.JButton();
        navLihatBahan = new javax.swing.JButton();
        navEditBahan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rexx\\Documents\\NetBeansProjects\\Laila\\AppTokoRoti\\src\\main\\resources\\assets\\Untitled-3.png")); // NOI18N

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(256, 256, 256))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab1", mainMenu);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tambah Bahan Baku");

        jLabel4.setText("Telur (kg) :");

        jLabel9.setText("Terigu (kg) :");

        jLabel10.setText("Garam (kg) :");

        jLabel11.setText("Gula (kg) :");

        jLabel12.setText("Susu (kg) :");

        tambahBahanBaku.setText("Tambah");
        tambahBahanBaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBahanBakuActionPerformed(evt);
            }
        });

        inputTelur.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputTelurInputMethodTextChanged(evt);
            }
        });

        inputTerigu.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputTeriguInputMethodTextChanged(evt);
            }
        });

        inputGaram.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputGaramInputMethodTextChanged(evt);
            }
        });

        inputGula.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputGulaInputMethodTextChanged(evt);
            }
        });

        inputSusu.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputSusuInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout panelTambahLayout = new javax.swing.GroupLayout(panelTambah);
        panelTambah.setLayout(panelTambahLayout);
        panelTambahLayout.setHorizontalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahLayout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(320, 320, 320))
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambahBahanBaku)
                    .addGroup(panelTambahLayout.createSequentialGroup()
                        .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputTelur)
                            .addComponent(inputTerigu)
                            .addComponent(inputGaram)
                            .addComponent(inputGula)
                            .addComponent(inputSusu, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTambahLayout.setVerticalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTambahLayout.createSequentialGroup()
                        .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(panelTambahLayout.createSequentialGroup()
                                .addComponent(inputTelur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputTerigu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addComponent(inputGaram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inputGula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(inputSusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahBahanBaku)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab2", panelTambah);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Edit Bahan Baku");

        jLabel7.setText("Masukkan kode produk");

        bCariEditProduk.setText("Cari");
        bCariEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariEditProdukActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        taEdit.setColumns(20);
        taEdit.setRows(5);
        taEdit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                taEditInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(taEdit);

        jLabel13.setText("Masukkan Perubahan Jumlah (kg) :");

        cariEdit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cariEditInputMethodTextChanged(evt);
            }
        });

        editJumlah.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                editJumlahInputMethodTextChanged(evt);
            }
        });

        bSimpanEdit.setText("Simpan");
        bSimpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel6))
                    .addGroup(panelEditLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bCariEditProduk)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2)
                                .addComponent(cariEdit)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEditLayout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(editJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelEditLayout.createSequentialGroup()
                                .addComponent(bHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSimpanEdit)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCariEditProduk)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(editJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHapus)
                    .addComponent(bSimpanEdit))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab3", panelEdit);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Lihat Bahan Baku");

        bCariLihatProduk.setText("Cari");
        bCariLihatProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariLihatProdukActionPerformed(evt);
            }
        });

        cariBahan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cariBahanInputMethodTextChanged(evt);
            }
        });

        outputLihat.setColumns(20);
        outputLihat.setRows(5);
        outputLihat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                outputLihatInputMethodTextChanged(evt);
            }
        });
        jScrollPane3.setViewportView(outputLihat);

        javax.swing.GroupLayout panelLihatLayout = new javax.swing.GroupLayout(panelLihat);
        panelLihat.setLayout(panelLihatLayout);
        panelLihatLayout.setHorizontalGroup(
            panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLihatLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cariBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLihatLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addGroup(panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLihatLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(276, 276, 276))
                            .addComponent(bCariLihatProduk)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panelLihatLayout.setVerticalGroup(
            panelLihatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLihatLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariBahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCariLihatProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab5", panelLihat);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabUtama, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabUtama)
        );

        navMainMenu.setText("Main Menu");
        navMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navMainMenuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kelola Bahan Baku");

        navTambahBahan.setText("Tambah Bahan Baku");
        navTambahBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navTambahBahanActionPerformed(evt);
            }
        });

        navLihatBahan.setText("Lihat Bahan Baku");
        navLihatBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLihatBahanActionPerformed(evt);
            }
        });

        navEditBahan.setText("Edit Bahan Baku");
        navEditBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navEditBahanActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rexx\\Documents\\NetBeansProjects\\Laila\\AppTokoRoti\\src\\main\\resources\\assets\\Untitled-2.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navTambahBahan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(navLihatBahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navEditBahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)))
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navTambahBahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navLihatBahan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navEditBahan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navMainMenuActionPerformed
        tabUtama.setSelectedComponent(mainMenu);
    }//GEN-LAST:event_navMainMenuActionPerformed

    private void navTambahBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navTambahBahanActionPerformed
        tabUtama.setSelectedComponent(panelTambah);
    }//GEN-LAST:event_navTambahBahanActionPerformed

    private void navLihatBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLihatBahanActionPerformed
        tabUtama.setSelectedComponent(panelLihat);
    }//GEN-LAST:event_navLihatBahanActionPerformed

    private void navEditBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navEditBahanActionPerformed
        tabUtama.setSelectedComponent(panelEdit);
    }//GEN-LAST:event_navEditBahanActionPerformed

//GEN-FIRST:event_textLihatProdukInputMethodTextChanged
 
//GEN-LAST:event_textLihatProdukInputMethodTextChanged

    // button cari di menu lihat produk
    private void bCariLihatProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariLihatProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariLihatProdukActionPerformed

   // button hapus produk
    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed

//GEN-FIRST:event_bSimpanEditProdukActionPerformed
 
//GEN-LAST:event_bSimpanEditProdukActionPerformed

//GEN-FIRST:event_editHargaProdukInputMethodTextChanged
 
//GEN-LAST:event_editHargaProdukInputMethodTextChanged

    // button cari di edit produk
    private void bCariEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariEditProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariEditProdukActionPerformed

//GEN-FIRST:event_cariEditKodeProdukInputMethodTextChanged
 
//GEN-LAST:event_cariEditKodeProdukInputMethodTextChanged

//GEN-FIRST:event_tambahHargaProdukInputMethodTextChanged
 
//GEN-LAST:event_tambahHargaProdukInputMethodTextChanged

//GEN-FIRST:event_tambahJenisProdukInputMethodTextChanged
 
//GEN-LAST:event_tambahJenisProdukInputMethodTextChanged

//GEN-FIRST:event_tambahNamaProdukInputMethodTextChanged
 
//GEN-LAST:event_tambahNamaProdukInputMethodTextChanged

//GEN-FIRST:event_tambahKodeProdukInputMethodTextChanged
 
//GEN-LAST:event_tambahKodeProdukInputMethodTextChanged

    private void tambahBahanBakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBahanBakuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahBahanBakuActionPerformed

    private void cariBahanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cariBahanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cariBahanInputMethodTextChanged

    private void cariEditInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cariEditInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cariEditInputMethodTextChanged

    private void taEditInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_taEditInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_taEditInputMethodTextChanged

    private void editJumlahInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_editJumlahInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_editJumlahInputMethodTextChanged

    private void inputTelurInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputTelurInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelurInputMethodTextChanged

    private void inputTeriguInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputTeriguInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTeriguInputMethodTextChanged

    private void inputGaramInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputGaramInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGaramInputMethodTextChanged

    private void inputGulaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputGulaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGulaInputMethodTextChanged

    private void inputSusuInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputSusuInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSusuInputMethodTextChanged

    private void outputLihatInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_outputLihatInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_outputLihatInputMethodTextChanged

    private void bSimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSimpanEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new UI_Manager().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCariEditProduk;
    private javax.swing.JButton bCariLihatProduk;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpanEdit;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField cariBahan;
    private javax.swing.JTextField cariEdit;
    private javax.swing.JTextField editJumlah;
    private javax.swing.JTextField inputGaram;
    private javax.swing.JTextField inputGula;
    private javax.swing.JTextField inputSusu;
    private javax.swing.JTextField inputTelur;
    private javax.swing.JTextField inputTerigu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton navEditBahan;
    private javax.swing.JButton navLihatBahan;
    private javax.swing.JButton navMainMenu;
    private javax.swing.JButton navTambahBahan;
    private javax.swing.JTextArea outputLihat;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelLihat;
    private javax.swing.JPanel panelTambah;
    private javax.swing.JTextArea taEdit;
    private javax.swing.JTabbedPane tabUtama;
    private javax.swing.JButton tambahBahanBaku;
    // End of variables declaration//GEN-END:variables
}
