/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.apptokoroti;

/**
 *
 * @author Rexx
 */
public class UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UI.class.getName());

    /**
     * Creates new form UI
     */
    public UI() {
    initComponents();

    tabUtama.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {

        @Override
        protected int calculateTabAreaHeight(
            int tabPlacement,
            int horizRunCount,
            int maxTabHeight
        ) {
            return 0;
        }

        @Override
        protected void paintTabArea(
            java.awt.Graphics g,
            int tabPlacement,
            int selectedIndex
        ) {
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        tabUtama = new javax.swing.JTabbedPane();
        mainMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tambahProduk = new javax.swing.JPanel();
        kodeProduk = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        bTambahProduk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        editProduk = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bCariEditProduk = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        bSimpanEditProduk = new javax.swing.JButton();
        bHapusProduk = new javax.swing.JButton();
        lihatProduk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        bCariLihatProduk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tambahKaryawan = new javax.swing.JPanel();
        addKodeKaryawan = new javax.swing.JTextField();
        addNamaKaryawan = new javax.swing.JTextField();
        addLevelKaryawan = new javax.swing.JTextField();
        addGajiKaryawan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        editKaryawan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cariEditKodeKaryawan = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        editKodeKaryawan = new javax.swing.JTextField();
        editNamaKaryawan = new javax.swing.JTextField();
        editLevelKaryawan = new javax.swing.JTextField();
        editGajiKaryawan = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        lihatKaryawan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cariLihatKaryawan = new javax.swing.JTextField();
        bCariLihatKaryawan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        navMainMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        navTambahProduk = new javax.swing.JButton();
        navLihatProduk = new javax.swing.JButton();
        navEditProduk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        navTambahKaryawan = new javax.swing.JButton();
        navLihatKaryawan = new javax.swing.JButton();
        navEditKaryawan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rexx\\Documents\\NetBeansProjects\\Laila\\AppTokoRoti\\src\\main\\resources\\assets\\Untitled-3.png")); // NOI18N

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(256, 256, 256))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab1", mainMenu);

        kodeProduk.setText("Masukkan kode produk");
        kodeProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeProdukActionPerformed(evt);
            }
        });

        jTextField2.setText("Masukkan nama produk");

        jTextField3.setText("Masukkan jenis produk");

        jTextField4.setText("Masukkan harga produk");

        bTambahProduk.setText("Simpan");
        bTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahProdukActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tambah Produk");

        javax.swing.GroupLayout tambahProdukLayout = new javax.swing.GroupLayout(tambahProduk);
        tambahProduk.setLayout(tambahProdukLayout);
        tambahProdukLayout.setHorizontalGroup(
            tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahProdukLayout.createSequentialGroup()
                .addGroup(tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bTambahProduk)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tambahProdukLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahProdukLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(kodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tambahProdukLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel5)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        tambahProdukLayout.setVerticalGroup(
            tambahProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahProdukLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTambahProduk)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab2", tambahProduk);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Edit Produk");

        jLabel7.setText("Masukkan kode produk");

        bCariEditProduk.setText("Cari");
        bCariEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariEditProdukActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        bSimpanEditProduk.setText("Simpan");
        bSimpanEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanEditProdukActionPerformed(evt);
            }
        });

        bHapusProduk.setText("Hapus Produk");
        bHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editProdukLayout = new javax.swing.GroupLayout(editProduk);
        editProduk.setLayout(editProdukLayout);
        editProdukLayout.setHorizontalGroup(
            editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProdukLayout.createSequentialGroup()
                .addGroup(editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProdukLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editProdukLayout.createSequentialGroup()
                                .addComponent(bHapusProduk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSimpanEditProduk))
                            .addGroup(editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bCariEditProduk)
                                .addComponent(jTextField1)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5)
                                .addComponent(jTextField6)
                                .addComponent(jTextField7)
                                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))))
                    .addGroup(editProdukLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel6)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        editProdukLayout.setVerticalGroup(
            editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProdukLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCariEditProduk)
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpanEditProduk)
                    .addComponent(bHapusProduk))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab3", editProduk);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Lihat Produk");

        bCariLihatProduk.setText("Cari");
        bCariLihatProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariLihatProdukActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout lihatProdukLayout = new javax.swing.GroupLayout(lihatProduk);
        lihatProduk.setLayout(lihatProdukLayout);
        lihatProdukLayout.setHorizontalGroup(
            lihatProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatProdukLayout.createSequentialGroup()
                .addGroup(lihatProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCariLihatProduk)
                    .addGroup(lihatProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(lihatProdukLayout.createSequentialGroup()
                            .addGap(314, 314, 314)
                            .addComponent(jLabel8))
                        .addGroup(lihatProdukLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        lihatProdukLayout.setVerticalGroup(
            lihatProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatProdukLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCariLihatProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab5", lihatProduk);

        addKodeKaryawan.setText("Masukkan kode karyawan");
        addKodeKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKodeKaryawanActionPerformed(evt);
            }
        });

        addNamaKaryawan.setText("Masukkan nama karyawan");

        addLevelKaryawan.setText("Masukkan level karyawan");

        addGajiKaryawan.setText("Masukkan gaji karyawan");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tambah Karyawan");

        jButton12.setText("Tambah");

        javax.swing.GroupLayout tambahKaryawanLayout = new javax.swing.GroupLayout(tambahKaryawan);
        tambahKaryawan.setLayout(tambahKaryawanLayout);
        tambahKaryawanLayout.setHorizontalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahKaryawanLayout.createSequentialGroup()
                .addGroup(tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12)
                    .addComponent(addGajiKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLevelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tambahKaryawanLayout.createSequentialGroup()
                            .addGap(318, 318, 318)
                            .addComponent(jLabel9))
                        .addGroup(tambahKaryawanLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(addKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        tambahKaryawanLayout.setVerticalGroup(
            tambahKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahKaryawanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addLevelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addGajiKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab6", tambahKaryawan);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Edit Karyawan");

        jLabel11.setText("Masukkan kode karyawan");

        jButton13.setText("Cari");

        jButton14.setText("Simpan");

        jButton15.setText("Hapus");

        javax.swing.GroupLayout editKaryawanLayout = new javax.swing.GroupLayout(editKaryawan);
        editKaryawan.setLayout(editKaryawanLayout);
        editKaryawanLayout.setHorizontalGroup(
            editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editKaryawanLayout.createSequentialGroup()
                .addGroup(editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editKaryawanLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel10))
                    .addGroup(editKaryawanLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editKaryawanLayout.createSequentialGroup()
                                .addComponent(jButton15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14))
                            .addGroup(editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton13)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cariEditKodeKaryawan)
                                .addComponent(editKodeKaryawan)
                                .addComponent(editNamaKaryawan)
                                .addComponent(editLevelKaryawan)
                                .addComponent(editGajiKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        editKaryawanLayout.setVerticalGroup(
            editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editKaryawanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariEditKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editKodeKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editLevelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editGajiKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab7", editKaryawan);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Lihat Karyawan");

        bCariLihatKaryawan.setText("Cari");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout lihatKaryawanLayout = new javax.swing.GroupLayout(lihatKaryawan);
        lihatKaryawan.setLayout(lihatKaryawanLayout);
        lihatKaryawanLayout.setHorizontalGroup(
            lihatKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lihatKaryawanLayout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(329, 329, 329))
            .addGroup(lihatKaryawanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lihatKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addComponent(bCariLihatKaryawan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cariLihatKaryawan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lihatKaryawanLayout.setVerticalGroup(
            lihatKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatKaryawanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariLihatKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCariLihatKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabUtama.addTab("tab9", lihatKaryawan);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabUtama, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabUtama)
        );

        navMainMenu.setText("Main Menu");
        navMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navMainMenuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kelola Produk");

        navTambahProduk.setText("Tambah Produk");
        navTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navTambahProdukActionPerformed(evt);
            }
        });

        navLihatProduk.setText("Lihat Produk");
        navLihatProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLihatProdukActionPerformed(evt);
            }
        });

        navEditProduk.setText("Edit Produk");
        navEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navEditProdukActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kelola Karyawan");

        navTambahKaryawan.setText("Tambah Karyawan");
        navTambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navTambahKaryawanActionPerformed(evt);
            }
        });

        navLihatKaryawan.setText("Lihat Karyawan");
        navLihatKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLihatKaryawanActionPerformed(evt);
            }
        });

        navEditKaryawan.setText("Edit Karyawan");
        navEditKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navEditKaryawanActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rexx\\Documents\\NetBeansProjects\\Laila\\AppTokoRoti\\src\\main\\resources\\assets\\Untitled-2.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navTambahProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navLihatProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navEditProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navTambahKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(navLihatKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navEditKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)))
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navTambahProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navLihatProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navEditProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navTambahKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navLihatKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navEditKaryawan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodeProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeProdukActionPerformed
    // button cari di edit produk
    private void bCariEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariEditProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariEditProdukActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed
    // button cari di menu lihat produk
    private void bCariLihatProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariLihatProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariLihatProdukActionPerformed

    private void addKodeKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKodeKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addKodeKaryawanActionPerformed

    private void navMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navMainMenuActionPerformed
        tabUtama.setSelectedComponent(mainMenu);
    }//GEN-LAST:event_navMainMenuActionPerformed

    private void navTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navTambahProdukActionPerformed
        tabUtama.setSelectedComponent(tambahProduk);
    }//GEN-LAST:event_navTambahProdukActionPerformed

    private void navLihatProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLihatProdukActionPerformed
        tabUtama.setSelectedComponent(lihatProduk);
    }//GEN-LAST:event_navLihatProdukActionPerformed

    private void navEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navEditProdukActionPerformed
        tabUtama.setSelectedComponent(editProduk);
    }//GEN-LAST:event_navEditProdukActionPerformed

    private void navTambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navTambahKaryawanActionPerformed
        tabUtama.setSelectedComponent(tambahKaryawan);
    }//GEN-LAST:event_navTambahKaryawanActionPerformed

    private void navLihatKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLihatKaryawanActionPerformed
        tabUtama.setSelectedComponent(lihatKaryawan);
    }//GEN-LAST:event_navLihatKaryawanActionPerformed

    private void navEditKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navEditKaryawanActionPerformed
        tabUtama.setSelectedComponent(editKaryawan);
    }//GEN-LAST:event_navEditKaryawanActionPerformed
    // button di menu tambah produk
    private void bTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTambahProdukActionPerformed
    // button hapus produk
    private void bHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusProdukActionPerformed
    // button simpan di menu edit produk
    private void bSimpanEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanEditProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSimpanEditProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addGajiKaryawan;
    private javax.swing.JTextField addKodeKaryawan;
    private javax.swing.JTextField addLevelKaryawan;
    private javax.swing.JTextField addNamaKaryawan;
    private javax.swing.JButton bCariEditProduk;
    private javax.swing.JButton bCariLihatKaryawan;
    private javax.swing.JButton bCariLihatProduk;
    private javax.swing.JButton bHapusProduk;
    private javax.swing.JButton bSimpanEditProduk;
    private javax.swing.JButton bTambahProduk;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField cariEditKodeKaryawan;
    private javax.swing.JTextField cariLihatKaryawan;
    private javax.swing.JTextField editGajiKaryawan;
    private javax.swing.JPanel editKaryawan;
    private javax.swing.JTextField editKodeKaryawan;
    private javax.swing.JTextField editLevelKaryawan;
    private javax.swing.JTextField editNamaKaryawan;
    private javax.swing.JPanel editProduk;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField kodeProduk;
    private javax.swing.JPanel lihatKaryawan;
    private javax.swing.JPanel lihatProduk;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton navEditKaryawan;
    private javax.swing.JButton navEditProduk;
    private javax.swing.JButton navLihatKaryawan;
    private javax.swing.JButton navLihatProduk;
    private javax.swing.JButton navMainMenu;
    private javax.swing.JButton navTambahKaryawan;
    private javax.swing.JButton navTambahProduk;
    private javax.swing.JTabbedPane tabUtama;
    private javax.swing.JPanel tambahKaryawan;
    private javax.swing.JPanel tambahProduk;
    // End of variables declaration//GEN-END:variables
}
